//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addmintracking
    {
        public int mintrackingid { get; set; }
        public Nullable<int> tenderid { get; set; }
        public string ipaddress { get; set; }
        public Nullable<int> clientid { get; set; }
        public Nullable<int> Addmin { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
