//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int bidid { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> Clientid { get; set; }
        public Nullable<System.DateTime> BiddateTime { get; set; }
        public Nullable<int> BidPrice { get; set; }
        public string ipaddress { get; set; }
    
        public virtual TenderItem TenderItem { get; set; }
        public virtual LoginMaster LoginMaster { get; set; }
    }
}
