//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.Suppliers = new HashSet<Supplier>();
            this.Tenders = new HashSet<Tender>();
        }
    
        public int CompanyId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Tender> Tenders { get; set; }
        public virtual LoginMaster LoginMaster { get; set; }
    }
}
