//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginMaster
    {
        public LoginMaster()
        {
            this.Bids = new HashSet<Bid>();
            this.companies = new HashSet<company>();
            this.Notifications = new HashSet<Notification>();
            this.Tenders = new HashSet<Tender>();
            this.Trackings = new HashSet<Tracking>();
        }
    
        public int ClientId { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LoginIP { get; set; }
        public byte[] clientpassword { get; set; }
        public string randompassword { get; set; }
        public Nullable<int> Defaultpass { get; set; }
    
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<company> companies { get; set; }
        public virtual RegisterMaster RegisterMaster { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Tender> Tenders { get; set; }
        public virtual ICollection<Tracking> Trackings { get; set; }
    }
}
