//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinPeriod
    {
        public MinPeriod()
        {
            this.Tenders = new HashSet<Tender>();
        }
    
        public int id { get; set; }
        public string TimePeriod { get; set; }
        public Nullable<System.TimeSpan> Value { get; set; }
        public Nullable<int> mins { get; set; }
    
        public virtual ICollection<Tender> Tenders { get; set; }
    }
}
