//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int id { get; set; }
        public Nullable<int> Tenderid { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> NotifyDateTime { get; set; }
        public string NotifyText { get; set; }
    
        public virtual Tender Tender { get; set; }
        public virtual LoginMaster LoginMaster { get; set; }
    }
}
