//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterMaster
    {
        public RegisterMaster()
        {
            this.LoginMasters = new HashSet<LoginMaster>();
        }
    
        public int RegisterId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> RegisterRole { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson { get; set; }
        public string RegAddress { get; set; }
        public string City { get; set; }
        public int pincode { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string PanNo { get; set; }
        public string Tin { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        public virtual Rolemaster Rolemaster { get; set; }
        public virtual ICollection<LoginMaster> LoginMasters { get; set; }
    }
}
