//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusMaster
    {
        public StatusMaster()
        {
            this.Suppliers = new HashSet<Supplier>();
            this.Trackings = new HashSet<Tracking>();
            this.Tenders = new HashSet<Tender>();
            this.LoginMasters = new HashSet<LoginMaster>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<Tracking> Trackings { get; set; }
        public virtual ICollection<Tender> Tenders { get; set; }
        public virtual ICollection<LoginMaster> LoginMasters { get; set; }
    }
}
