//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tender
    {
        public Tender()
        {
            this.Notifications = new HashSet<Notification>();
            this.Suppliers = new HashSet<Supplier>();
            this.TenderItems = new HashSet<TenderItem>();
            this.Trackings = new HashSet<Tracking>();
            this.tenderInvoices = new HashSet<tenderInvoice>();
        }
    
        public int TenderId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Attachment { get; set; }
        public string TenderDesc { get; set; }
        public System.DateTime StartDate { get; set; }
        public string StartTime { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string Endtime { get; set; }
        public Nullable<int> TimePeriod { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Tstatus { get; set; }
        public string terms { get; set; }
        public string WF_No { get; set; }
    
        public virtual company company1 { get; set; }
        public virtual MinPeriod MinPeriod { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual ICollection<TenderItem> TenderItems { get; set; }
        public virtual ICollection<Tracking> Trackings { get; set; }
        public virtual LoginMaster LoginMaster { get; set; }
        public virtual ICollection<tenderInvoice> tenderInvoices { get; set; }
    }
}
