//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenderInvoice
    {
        public int tenderinvoiceid { get; set; }
        public Nullable<int> tenderid { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<int> PoentryBy { get; set; }
        public string vendorname { get; set; }
        public Nullable<System.DateTime> poentrydate { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> invoiceentryby { get; set; }
        public Nullable<System.DateTime> invoiceentrydate { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Tender Tender { get; set; }
    }
}
