//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_bidmin_record
    {
        public int bidid { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> clientid { get; set; }
        public Nullable<int> bidprice { get; set; }
    }
}
